### ISSUE TITLE
Bot only outputs usage when LANG environment variable does not match picked --language

### ISSUE THREAD

**Issue by cobalamin** [felsenhower/stine_calendar_bot#7]
When calling the bot like

`java -jar stine_calendar_bot.jar --user=... --language=de --pass=-- --output=stine.ics`

but the terminal's language does not match the option, e.g., it is `en_US.utf8` instead, the tool will only output the usage string and won't run.

Users can work around this by exporting the correct language via, e.g., `LANG=de_DE.utf8` and then running the original command again. (Or by supplying the `LANG` env variable before the command without exporting.)

**Comment by felsenhower** [comment]
The `--language` option seems to be completely broken.

I will probably remove the feature to automatically detect the system language and make `--language` mandatory.

**Comment by felsenhower** [comment]
Should be fixed with f604bc4c2b70b5f501f27d0394f80880e53b1dbb.
